### ISSUE TITLE
Cant uninstall mod

### ISSUE THREAD

**Issue by helloamme** [MineLittlePony/Kirin#6]
So I installed some mods and idk why but I got your mod
And, I can't uninstall it cause there is no file about it in the mods folder
so please help me

**Comment by mattmess1221** [comment]
It is probably bundled with another mod like HDSkins, MineLittlePony, or Unicopia.

I believe the mod ModMenu can show you what mods depend on other mods.

**Comment by keupoz** [comment]
I also know there are other mods that depend on this mod because this mod is a GUI library

**Comment by Sollace** [comment]
Kirin is a library that's intended to be used by other mods, so it 100% is being included by one of the mods you installed. If they're using it, Kirin is very much _required_ so you shouldn't try to remove it.

It doesn't do anything on its own anyway, so it simply being there is harmless.
